### ISSUE TITLE
Fix PR workflow check for dependabot updates

### ISSUE THREAD

**Issue by mishomihov00** [hashgraph/hedera-metamask-snaps#791]
### Description

When dependabot creates a new PR the `wallet-snap-analyze` job from the `flow-pull-request-checks.yaml` workflow is skipped because of the if statement which is configured to skip the job if the PR is coming from dependabot, but this job is required for PR merging which leads to a "deadlock" and the inability to merge dependabot PR's.

### Steps to reproduce

Wait for dependabot to create a PR and look at the checks.

### Additional context

Example PR's:
#789 
#790 

### Version

latest

### Operating system

None

**Comment by mishomihov00** [comment]
@hashgraph/devops-ci another possible solution to this problem is just to remove the "Required" field for this job. If you think doing that is better, please feel free to discard this ticket and the PR.

**Comment by rbarkerSL** [comment]
We should keep the dependabot check in here and force the repository owners to merge these bumps coming from dependabot.

**Comment by mishomihov00** [comment]
@rbarkerSL understood. Closing the PR and the issue.
